pipeline:
  build:
    image: docker
    environment:
      LOCAL_DOCKER_REGISTRY:
        from_secret: local_docker_registry
    commands:
      - docker build . -t $LOCAL_DOCKER_REGISTRY/citadel
      - docker push $LOCAL_DOCKER_REGISTRY/citadel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

trigger:
  branch:
  - master
  event:
    - push
    - pull_request
    - tag
