
pipeline:
  build:
    image: docker
    local_docker_registry:
      from_secret: local_docker_registry
    commands:
      - docker build . -t $PLUGIN_LOCAL_DOCKER_REGISTRY/citadel
      - docker push $PLUGIN_LOCAL_DOCKER_REGISTRY/citadel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

trigger:
  branch:
  - master
  event:
    - push
    - pull_request
    - tag
